### ISSUE TITLE
[QUESTION] WIll the documentation website be opensource?

### ISSUE THREAD

**Issue by acuaroo** [astrealRBLX/volt#1]
Title says it all, I am saying this because of a few things.
- The current docs are very non-verbose
- The current docs could use more examples
- There are a few typos here and there

If they do, I'd be glad to contribute to fix a few of these, just wondering if it ever will be.

**Comment by acuaroo** [comment]
Whoops, just noticed the second branch

**Comment by astrealRBLX** [comment]
Glad to hear you're interested in contributing. I've added the `docs` directory used to create the documentation to the main branch. You can contribute to this as its significantly easier to work with than the built site and will override anything currently built.

https://github.com/astrealRBLX/volt/tree/main/docs
