### ISSUE TITLE
Tween page & Promise pages are absolutely useless

### ISSUE THREAD

**Issue by acuaroo** [astrealRBLX/volt#5]
Right now, the [tween page](https://astrealrblx.github.io/volt/libs/tween/) inside library -> utilities in the documentation, it only contains...

![Screen Shot 2021-06-05 at 9 55 02 AM](https://user-images.githubusercontent.com/67112172/120897571-1c1fe600-c5e4-11eb-899c-dde6c449390c.png)

This is not verbose at all, and unlike the other libs, doesn't contain any examples.

The [promise page](https://astrealrblx.github.io/volt/libs/promise/) points towards documentation. While this is fine, it should contain an example or overview from the promise documentation **and then** differ the user to the promise documentation.

**Comment by astrealRBLX** [comment]
Fixed with https://github.com/astrealRBLX/volt/commit/49fc77fce1c4ba7df9ac0012d92170e81b427cd9
